openapi: 3.0.0
info:
  title: Policy API
  description: This API allows policy management (get policy and convert policy).
  contact:
    email: lopez.rodrigo@kopernicus.tech
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 3.0.0
servers:
- url: https://virtserver.swaggerhub.com/Rlopezg/Policy/3.0.0
  description: SwaggerHub API Auto Mocking
- url: https://prod.swaggerhub.com/Rlopezg/Policy/2.0.0
  description: URL de producci贸n
- url: https://desa.swaggerhub.com/Rlopezg/polizas/2.0.0
  description: URL de UAT
tags:
- name: contract
  description: This API belongs to "Contract" domain.
paths:
  /policies:
    get:
      summary: Get policies.
      description: Allows you to obtain a list of policies. The searchString parameter
        is optional and can be used to obtain subsets of policies.
      operationId: getPolicies
      parameters:
      - name: searchString
        in: query
        description: Pass an optional search string for looking up policies.
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: offset
        in: query
        description: Page number for pagination.
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          format: int32
      - name: limit
        in: query
        description: Maximum number of records to return.
        required: false
        style: form
        explode: true
        schema:
          maximum: 50
          minimum: 0
          type: integer
          format: int32
      responses:
        "200":
          description: Search results matching criteria.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Policy'
        "400":
          description: Bad input parameter.
    post:
      summary: Convert (contract) a new policy.
      description: Create a new policy in state 0 (Contract).
      operationId: convertPolicy
      requestBody:
        description: 'Policy to add:'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Policy'
      responses:
        "201":
          description: Policy converted (contracted) succefully.
        "400":
          description: "Invalid input, object invalid."
        "409":
          description: An existing policy already exists.
components:
  schemas:
    Policy:
      required:
      - insuredObjects
      - policyHolder
      - policyNumber
      - productType
      - startDate
      type: object
      properties:
        id:
          type: number
          description: Internal ID generated by the system.
          example: 3453454532
        policyNumber:
          type: string
          description: Business policy number.
          example: "4352"
        peoductType:
          $ref: '#/components/schemas/Product'
        startDate:
          type: string
          description: Start vigency date.
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        endDate:
          type: string
          description: End vigency date.
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        policyHolder:
          $ref: '#/components/schemas/Person'
        insuredObjects:
          type: array
          description: List of insured objects (asset or person).
          items:
            $ref: '#/components/schemas/InsuredObject'
      description: Contiene la informaci贸n principal de una p贸liza.
    Product:
      required:
      - businessId
      type: object
      properties:
        id:
          type: number
          description: Internal ID generated by the system.
          example: 3453454532
        businessId:
          type: string
          description: Business meaningfull code.
          example: FULL_LIFE_01
        description:
          type: string
          description: A brief description of the insurance comercial product.
          example: Full life great product!
      description: Represents a insurance product.
    Person:
      required:
      - businessId
      - name
      type: object
      properties:
        id:
          type: number
          description: Internal ID generated by the system.
          example: 76565665676
        businessId:
          type: string
          description: Identification document number.
          example: 13136234-5
        name:
          type: string
          description: Person's full name.
          example: Rodrigo L贸pez H.
        email:
          type: string
          example: doe@mail.com
      description: Represents a natural or legal person.
    InsuredObject:
      type: object
      properties:
        contractCoverages:
          type: array
          items:
            $ref: '#/components/schemas/ContractCoverage'
      description: Contains information about the insured object.
      oneOf:
      - $ref: '#/components/schemas/Object'
      - $ref: '#/components/schemas/Person'
    Object:
      required:
      - type
      type: object
      properties:
        id:
          type: number
          description: Internal ID generated by the system.
          example: 3453454532
        type:
          type: string
          example: Car
      description: Represents an object/asset (for general insurance purposes).
    ContractCoverage:
      required:
      - coverageType
      type: object
      properties:
        id:
          type: number
          description: Internal ID number generated by the system.
          example: 87687678
        coverageType:
          $ref: '#/components/schemas/CoverageType'
        premium:
          type: number
          example: 100.0
      description: Coverage contracted.
    CoverageType:
      required:
      - coverageType
      type: object
      properties:
        id:
          type: number
          description: Internal ID number generated by the system.
          example: 23532234
        coverageType:
          type: string
          example: Death
      description: Coverage type.
